[general]
live_config_reload = true
working_directory = "~/ghq"
[window]
opacity = 0.9
decorations = "None"
startup_mode ="Maximized"
level ="AlwaysOnTop"
[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 14.0

[keyboard]
bindings = [
{ key= "Right", mods= "Alt", chars="\u001BF" },
{ key= "Left",  mods= "Alt", chars="\u001BB" },
]
[env]
TERM = "alacritty"